FROM phpdockerio/php74-fpm:latest

RUN apt-get update \
    && apt-get -y --no-install-recommends install mysql-client php7.4-mysql php7.4-intl php7.4-mbstring php7.4-sqlite3\
    libicu-dev libzip-dev libpq-dev nano php-mongodb libmcrypt-dev git zip unzip\
    && apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

WORKDIR "/var/www/"

#RUN composer install --no-interaction