# Generated by Django 2.2.4 on 2020-12-09 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0012_auto_20201208_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='profundidad',
            new_name='profundidad_cm',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='tiempo_cultivo_dias',
            new_name='tiempo_cultivo_semanas',
        ),
    ]
