# Generated by Django 2.2.4 on 2020-12-09 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0013_auto_20201209_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='plantas.Tipo'),
        ),
    ]
