# Generated by Django 2.2.4 on 2020-12-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0015_auto_20201209_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nombre_cientifico',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
