# Generated by Django 2.2.4 on 2020-12-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0016_auto_20201227_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(choices=[('FR', 'Fruta'), ('FL', 'Flor'), ('HO', 'Hoja'), ('RA', 'Raiz')], max_length=200, null=True),
        ),
    ]
