# Generated by Django 2.2.4 on 2020-12-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0017_auto_20201227_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='desde',
            field=models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], default='ENE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta',
            field=models.CharField(choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], default='DIC', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='tipo',
            field=models.CharField(choices=[('SE', 'Semillero'), ('SI', 'Siembra'), ('TR', 'Trasplante'), ('CO', 'Cosecha')], default='SI', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='profundidad_cm',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tamano',
            field=models.CharField(choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra Grande')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tiempo_cultivo_semanas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='volumen_mazeta_ltr',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
