# Generated by Django 2.2.4 on 2020-12-27 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0018_auto_20201227_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='distancia',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horas_sol',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='riego',
            field=models.CharField(choices=[('c15D', 'Cada 15 días'), ('1xS', 'Una vez por semana'), ('2xS', 'Dos veces por semana'), ('c2D', 'Cada dos días'), ('1xD', 'Una vez por día'), ('2xD', 'Dos veces por día')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
