# Generated by Django 2.2.4 on 2020-12-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0019_auto_20201227_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='nombre_cientifico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='familia',
            name='nombre_popular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
