# Generated by Django 2.2.4 on 2020-12-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0020_auto_20201227_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='desde',
            field=models.CharField(blank=True, choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], default='ENE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta',
            field=models.CharField(blank=True, choices=[('ENE', 'Enero'), ('FEB', 'Febrero'), ('MAR', 'Marzo'), ('ABR', 'Abril'), ('MAY', 'Mayo'), ('JUN', 'Junio'), ('JUL', 'Julio'), ('AGO', 'Agosto'), ('SEP', 'Septiembre'), ('OCT', 'Octubre'), ('NOV', 'Noviembre'), ('DIC', 'Diciembre')], default='DIC', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='riego',
            field=models.CharField(blank=True, choices=[('c15D', 'Cada 15 días'), ('1xS', 'Una vez por semana'), ('2xS', 'Dos veces por semana'), ('c2D', 'Cada dos días'), ('1xD', 'Una vez por día'), ('2xD', 'Dos veces por día')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tiempo_cultivo_semanas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre_cientifico',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre_popular',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='planta',
            name='variedad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sustrato',
            name='tierra',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='nombre',
            field=models.CharField(blank=True, choices=[('FR', 'Fruta'), ('FL', 'Flor'), ('HO', 'Hoja'), ('RA', 'Raiz')], max_length=200, null=True),
        ),
    ]
