# Generated by Django 2.2.4 on 2020-12-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0021_auto_20201227_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='distancia',
        ),
        migrations.AddField(
            model_name='ficha',
            name='distancia_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='epoca_cosecha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_cosecha', to='plantas.Epoca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='epoca_semillero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_semillero', to='plantas.Epoca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='epoca_siembra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_siembra', to='plantas.Epoca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='epoca_trasplante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_trasplante', to='plantas.Epoca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='fuentes',
            field=models.ManyToManyField(blank=True, to='plantas.Fuente'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horas_sol',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='profundidad_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sustrato',
            field=models.ManyToManyField(blank=True, to='plantas.Sustrato'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tamano',
            field=models.CharField(blank=True, choices=[('S', 'Chico'), ('M', 'Mediano'), ('L', 'Grande'), ('XL', 'Extra Grande')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tips',
            field=models.ManyToManyField(blank=True, to='plantas.Tip'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='volumen_mazeta_ltr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tip',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
