# Generated by Django 2.2.4 on 2020-12-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0022_auto_20201227_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='volumen_mazeta_ltr',
            new_name='volumen_maceta_ltr',
        ),
    ]
