# Generated by Django 2.2.4 on 2020-12-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0023_auto_20201227_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacciones',
            name='actores',
        ),
        migrations.AddField(
            model_name='interacciones',
            name='benefica',
            field=models.ManyToManyField(blank=True, to='plantas.Planta'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='distancia_cm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='profundidad_cm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='temperatura',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='volumen_maceta_ltr',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
