# Generated by Django 2.2.4 on 2020-12-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0024_auto_20201227_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interacciones',
            name='tipo',
        ),
        migrations.AddField(
            model_name='interacciones',
            name='perjudicial',
            field=models.ManyToManyField(blank=True, related_name='Perjudicial', to='plantas.Planta'),
        ),
        migrations.AlterField(
            model_name='interacciones',
            name='benefica',
            field=models.ManyToManyField(blank=True, related_name='Benéfica', to='plantas.Planta'),
        ),
    ]
