# Generated by Django 2.2.4 on 2020-12-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0026_auto_20201228_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='sustrato',
            field=models.ManyToManyField(blank=True, related_name='Sutrato', to='plantas.Sustrato'),
        ),
    ]
