# Generated by Django 2.2.4 on 2020-12-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0027_auto_20201229_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='tipo',
            field=models.CharField(blank=True, choices=[('SE', 'Semillero'), ('SI', 'Siembra'), ('TR', 'Trasplante'), ('CO', 'Cosecha')], max_length=200, null=True),
        ),
    ]
