# Generated by Django 2.2.4 on 2020-12-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0028_auto_20201229_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='horas_sol',
            new_name='horas_sol_max',
        ),
        migrations.RenameField(
            model_name='ficha',
            old_name='temperatura',
            new_name='horas_sol_min',
        ),
        migrations.AddField(
            model_name='ficha',
            name='temperatura_max',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='temperatura_min',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
