# Generated by Django 2.2.4 on 2020-12-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0029_auto_20201229_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='descripcion',
            new_name='titulo',
        ),
    ]
