# Generated by Django 2.2.4 on 2020-12-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0030_auto_20201229_0430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fuente',
            name='autor',
        ),
        migrations.AlterField(
            model_name='fuente',
            name='cita',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='autores',
            field=models.ManyToManyField(blank=True, to='plantas.Autor'),
        ),
    ]
