# Generated by Django 2.2.4 on 2020-12-29 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0031_auto_20201229_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente',
            name='autores',
        ),
        migrations.AddField(
            model_name='fuente',
            name='autores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantas.Autor'),
        ),
    ]
