# Generated by Django 2.2.4 on 2020-12-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0032_auto_20201229_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente',
            name='autores',
        ),
        migrations.AddField(
            model_name='fuente',
            name='autores',
            field=models.ManyToManyField(blank=True, null=True, to='plantas.Autor'),
        ),
    ]
