# Generated by Django 2.2.4 on 2020-12-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0033_auto_20201229_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente',
            name='autores',
            field=models.ManyToManyField(blank=True, to='plantas.Autor'),
        ),
    ]
