# Generated by Django 2.2.4 on 2020-12-29 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0035_auto_20201229_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autororder',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantas.Autor'),
        ),
        migrations.AlterField(
            model_name='autororder',
            name='fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantas.Fuente'),
        ),
    ]
