# Generated by Django 2.2.4 on 2020-12-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0036_auto_20201229_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente',
            name='autores',
            field=models.ManyToManyField(blank=True, to='plantas.Autor'),
        ),
        migrations.DeleteModel(
            name='AutorOrder',
        ),
    ]
