# Generated by Django 2.2.4 on 2020-12-29 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0038_auto_20201229_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantas.Autor')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AlterField(
            model_name='fuente',
            name='autores',
            field=models.ManyToManyField(through='plantas.AutorOrder', to='plantas.Autor'),
        ),
        migrations.AddField(
            model_name='autororder',
            name='fuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plantas.Fuente'),
        ),
    ]
