# Generated by Django 2.2.4 on 2020-12-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0039_auto_20201229_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autororder',
            options={},
        ),
    ]
