# Generated by Django 2.2.4 on 2020-12-29 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0041_auto_20201229_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuente',
            name='autores',
        ),
        migrations.AddField(
            model_name='fuente',
            name='otros_autores',
            field=models.ManyToManyField(blank=True, to='plantas.Autor'),
        ),
        migrations.AddField(
            model_name='fuente',
            name='primer_autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primer_autor', to='plantas.Autor'),
        ),
    ]
