# Generated by Django 2.2.4 on 2020-12-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0042_auto_20201229_0829'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interacciones',
            new_name='Interaccion',
        ),
        migrations.RenameModel(
            old_name='Rotaciones',
            new_name='Rotacion',
        ),
    ]
