# Generated by Django 2.2.4 on 2020-12-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0043_auto_20201229_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='sombra',
            field=models.BooleanField(default=False),
        ),
    ]
