# Generated by Django 2.2.4 on 2020-12-29 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0044_ficha_sombra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='sombra',
            new_name='soporta_sombra',
        ),
    ]
