# Generated by Django 2.2.4 on 2021-01-02 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0045_auto_20201229_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorOrden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Autor')),
                ('fuente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantas.Fuente')),
            ],
            options={
                'ordering': ('orden',),
            },
        ),
        migrations.AddField(
            model_name='fuente',
            name='autores',
            field=models.ManyToManyField(blank=True, through='plantas.AutorOrden', to='plantas.Autor'),
        ),
    ]
