# Generated by Django 2.2.4 on 2021-01-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0047_auto_20210102_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaccion',
            name='actor',
            field=models.ManyToManyField(to='plantas.Planta'),
        ),
    ]
