# Generated by Django 2.2.4 on 2021-01-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0048_auto_20210102_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='planta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas', to='plantas.Planta'),
        ),
    ]
