# Generated by Django 2.2.4 on 2021-01-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0049_auto_20210102_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuente',
            old_name='cita',
            new_name='otros',
        ),
        migrations.AddField(
            model_name='fuente',
            name='titulo',
            field=models.TextField(blank=True),
        ),
    ]
