# Generated by Django 2.2.4 on 2021-01-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0050_auto_20210102_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='autor',
        ),
        migrations.AddField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='primer_nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='segundo_nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='acceso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='anio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='articulo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='capitulo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='contenido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='edicion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='editorial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='nombre_pag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='pag_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='pag_inicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='red_social',
            field=models.CharField(blank=True, choices=[('YT', 'Youtube'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('FB', 'Facebook')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='tipo',
            field=models.CharField(choices=[('LI', 'Libro'), ('RE', 'Revista'), ('PE', 'Periódico'), ('PW', 'Pagina web'), ('DI', 'Diccionario'), ('RS', 'Red social'), ('WP', 'Wikipedia'), ('PP', 'Power point')], default='LB', max_length=20),
        ),
        migrations.AddField(
            model_name='fuente',
            name='tipo_cont',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='usuario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuente',
            name='volumen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='otros',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
