# Generated by Django 2.2.4 on 2021-01-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0051_auto_20210103_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaccion',
            old_name='descripcion',
            new_name='relacion',
        ),
        migrations.AlterField(
            model_name='autor',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='tipo',
            field=models.CharField(choices=[('LI', 'Libro'), ('RE', 'Revista'), ('PE', 'Periódico'), ('PW', 'Pagina web'), ('DI', 'Diccionario'), ('RS', 'Red social'), ('WP', 'Wikipedia'), ('PP', 'Power point')], default='LI', max_length=20),
        ),
        migrations.AlterField(
            model_name='interaccion',
            name='tipo',
            field=models.CharField(choices=[('B', 'Benéfica'), ('P', 'Perjudicial')], default='B', max_length=10),
        ),
    ]
