# Generated by Django 2.2.4 on 2021-01-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0052_auto_20210109_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente',
            name='red_social',
            field=models.CharField(blank=True, choices=[('YT', 'Youtube'), ('TW', 'Twitter'), ('IN', 'Instagram'), ('FB', 'Facebook')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interaccion',
            name='relacion',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
