# Generated by Django 2.2.4 on 2021-01-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0054_auto_20210109_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='epocas',
        ),
        migrations.AddField(
            model_name='ficha',
            name='epocas',
            field=models.ManyToManyField(blank=True, null=True, related_name='epocas', to='plantas.Epoca'),
        ),
    ]
