# Generated by Django 2.2.4 on 2021-01-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0055_auto_20210109_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoca',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
