# Generated by Django 2.2.4 on 2021-01-10 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0056_epoca_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoca',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='epoca',
            name='desde_mes',
            field=models.CharField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default='ENE', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta_mes',
            field=models.CharField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default='DIC', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='epocas',
            field=models.ManyToManyField(blank=True, related_name='epocas', to='plantas.Epoca'),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='planta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha', to='plantas.Planta'),
        ),
    ]
