# Generated by Django 2.2.4 on 2021-01-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0063_auto_20210110_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuente',
            name='nombre_pag',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fuente',
            name='tipo',
            field=models.CharField(blank=True, choices=[('LI', 'Libro'), ('RE', 'Revista'), ('PE', 'Periódico'), ('PW', 'Pagina web'), ('DI', 'Diccionario'), ('RS', 'Red social'), ('WP', 'Wikipedia'), ('PP', 'Power point')], default=None, max_length=20, null=True),
        ),
    ]
