# Generated by Django 2.2.4 on 2021-01-11 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0064_auto_20210111_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='distancia_cm',
            new_name='distancia_max_cm',
        ),
        migrations.AddField(
            model_name='ficha',
            name='distancia_min_cm',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='desde_dia',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta_dia',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)]),
        ),
    ]
