# Generated by Django 2.2.4 on 2021-01-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0065_auto_20210111_1624'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.CheckConstraint(check=models.Q(('desde_dia__gte', 1), ('hasta_dia__gte', 1), ('desde_dia__lte', 31), ('hasta_dia__lte', 31)), name='Tiene que ser un entero entre 1 y 31'),
        ),
    ]
