# Generated by Django 2.2.4 on 2021-01-11 16:47

from django.db import migrations
import plantas.models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0066_auto_20210111_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='desde_dia',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
