# Generated by Django 2.2.4 on 2021-01-11 17:17

from django.db import migrations
import plantas.models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0067_auto_20210111_1647'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='epoca',
            name='Tiene que ser un entero entre 1 y 31',
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta_dia',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
