# Generated by Django 2.2.4 on 2021-01-11 17:21

from django.db import migrations
import plantas.models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0068_auto_20210111_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='distancia_max_cm',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='distancia_min_cm',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horas_sol_max',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='horas_sol_min',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='profundidad_cm',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='temperatura_max',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='temperatura_min',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='volumen_maceta_ltr',
            field=plantas.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
