# Generated by Django 2.2.4 on 2021-01-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0069_auto_20210111_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ficha',
            old_name='soporta_sombra',
            new_name='tolera_sombra',
        ),
    ]
