# Generated by Django 2.2.4 on 2021-01-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0072_ficha_tiempo_cultivo_max_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='hasta_mes',
            field=models.CharField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='12', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='tipo',
            field=models.CharField(blank=True, choices=[('AL', 'Almácigo'), ('SI', 'Siembra'), ('TR', 'Trasplante'), ('CO', 'Cosecha')], max_length=200, null=True),
        ),
    ]
