# Generated by Django 2.2.4 on 2021-01-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0073_auto_20210111_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='fecundacion',
            field=models.CharField(blank=True, choices=[('AU', 'Autofecundación'), ('CR', 'cruzada')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta_mes',
            field=models.CharField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=200, null=True),
        ),
    ]
