# Generated by Django 2.2.4 on 2021-01-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0075_auto_20210111_2018'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='epoca',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(fields=('tipo', 'desde_dia', 'desde_mes', 'hasta_dia', 'hasta_mes'), name='unique epoca'),
        ),
    ]
