# Generated by Django 2.2.4 on 2021-01-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0076_auto_20210111_2023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='epoca',
            unique_together={('tipo', 'desde_dia', 'desde_mes', 'hasta_dia', 'hasta_mes')},
        ),
    ]
