# Generated by Django 2.2.4 on 2021-01-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0077_auto_20210111_2058'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='epoca',
            unique_together=set(),
        ),
    ]
