# Generated by Django 2.2.4 on 2021-01-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0078_auto_20210112_1955'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique epoca',
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(fields=('tipo', 'desde_dia', 'desde_mes', 'hasta_dia', 'hasta_mes'), name='dia y mes unicos'),
        ),
    ]
