# Generated by Django 2.2.4 on 2021-01-13 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0079_auto_20210112_2015'),
    ]

    operations = [
        #migrations.RemoveConstraint(
        #    model_name='epoca',
        #    name='dia y mes unicos',
        #),
        migrations.AlterField(
            model_name='epoca',
            name='desde_mes',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta_mes',
            field=models.CharField(blank=True, choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='tipo',
            field=models.CharField(blank=True, choices=[('AL', 'Almácigo'), ('SI', 'Siembra'), ('TR', 'Trasplante'), ('CO', 'Cosecha')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(fields=('tipo', 'desde_dia', 'desde_mes', 'hasta_dia', 'hasta_mes'), name='unique days and months'),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(condition=models.Q(hasta_dia__isnull=True), fields=('tipo', 'desde_dia', 'desde_mes', 'hasta_mes'), name='unique desde_dia and months'),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(condition=models.Q(desde_dia__isnull=True), fields=('tipo', 'desde_dia', 'desde_mes', 'hasta_mes'), name='unique hasta_dia and months'),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(condition=models.Q(('desde_dia__isnull', True), ('hasta_dia__isnull', True)), fields=('tipo', 'desde_mes', 'hasta_mes'), name='unique months'),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(condition=models.Q(('desde_dia__isnull', True), ('hasta_dia__isnull', True), ('hasta_mes__isnull', True)), fields=('tipo', 'desde_mes', 'hasta_mes'), name='unique desde_mes'),
        ),
    ]
