# Generated by Django 2.2.4 on 2021-01-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0080_auto_20210113_0100'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='epoca',
            name='dia y mes unicos',
        ),
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique days and months',
        ),
    ]
