# Generated by Django 2.2.4 on 2021-01-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0081_auto_20210113_0128'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique desde_dia and months',
        ),
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique hasta_dia and months',
        ),
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique months',
        ),
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique desde_mes',
        ),
    ]
