# Generated by Django 2.2.4 on 2021-01-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0082_auto_20210113_0132'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(condition=models.Q(hasta_dia__isnull=True), fields=('tipo', 'desde_dia', 'desde_mes', 'hasta_mes'), name='unique desde_dia and months'),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(condition=models.Q(desde_dia__isnull=True), fields=('tipo', 'desde_dia', 'desde_mes', 'hasta_mes'), name='unique hasta_dia and months'),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(condition=models.Q(('desde_dia__isnull', True), ('hasta_dia__isnull', True)), fields=('tipo', 'desde_mes', 'hasta_mes'), name='unique months'),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(condition=models.Q(('desde_dia__isnull', True), ('hasta_dia__isnull', True), ('hasta_mes__isnull', True)), fields=('tipo', 'desde_mes', 'hasta_mes'), name='unique desde_mes'),
        ),
    ]
