# Generated by Django 2.2.4 on 2021-01-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0083_auto_20210113_0134'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(fields=('tipo', 'desde_dia', 'desde_mes', 'hasta_dia', 'hasta_mes'), name='unique days and months'),
        ),
    ]
