# Generated by Django 2.2.4 on 2021-01-13 03:03

from django.db import migrations
import plantas.models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0085_auto_20210113_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='desde_dia',
            field=plantas.models.IntegerRangeField(blank=True, default=0),
        ),
    ]
