# Generated by Django 2.2.4 on 2021-01-13 03:15

from django.db import migrations
import plantas.models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0086_auto_20210113_0303'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique desde_dia and months',
        ),
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique hasta_dia and months',
        ),
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique months',
        ),
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique desde_mes',
        ),
        migrations.RemoveConstraint(
            model_name='epoca',
            name='unique days and months',
        ),
        migrations.AlterField(
            model_name='epoca',
            name='desde_dia',
            field=plantas.models.IntegerRangeField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='epoca',
            unique_together={('tipo', 'desde_dia', 'desde_mes', 'hasta_dia', 'hasta_mes')},
        ),
    ]
