# Generated by Django 2.2.4 on 2021-01-13 03:17

from django.db import migrations
import plantas.models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0087_auto_20210113_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='desde_dia',
            field=plantas.models.IntegerRangeField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta_dia',
            field=plantas.models.IntegerRangeField(blank=True, default=0, null=True),
        ),
    ]
