# Generated by Django 2.2.4 on 2021-01-13 03:20

from django.db import migrations, models
import plantas.models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0088_auto_20210113_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoca',
            name='desde_dia',
            field=plantas.models.IntegerRangeField(default=0),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta_dia',
            field=plantas.models.IntegerRangeField(default=0),
        ),
        migrations.AlterField(
            model_name='epoca',
            name='hasta_mes',
            field=models.CharField(choices=[('1', 'Enero'), ('2', 'Febrero'), ('3', 'Marzo'), ('4', 'Abril'), ('5', 'Mayo'), ('6', 'Junio'), ('7', 'Julio'), ('8', 'Agosto'), ('9', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='12', max_length=20),
        ),
    ]
