# Generated by Django 2.2.4 on 2021-01-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0089_auto_20210113_0320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='epoca',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='epoca',
            constraint=models.UniqueConstraint(fields=('tipo', 'desde_dia', 'desde_mes', 'hasta_dia', 'hasta_mes'), name='unique days and months'),
        ),
    ]
