# Generated by Django 2.2.4 on 2021-01-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0090_auto_20210113_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
        migrations.AlterModelOptions(
            name='autororden',
            options={'ordering': ('orden',), 'verbose_name': 'Autor orden', 'verbose_name_plural': 'Autor ordenes'},
        ),
        migrations.AlterModelOptions(
            name='interaccion',
            options={'verbose_name': 'Interacción', 'verbose_name_plural': 'Interacciones'},
        ),
        migrations.AlterModelOptions(
            name='rotacion',
            options={'verbose_name': 'Rotación', 'verbose_name_plural': 'Rotaciones'},
        ),
    ]
