# Generated by Django 2.2.4 on 2021-01-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0091_auto_20210114_0032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'ordering': ('nombre_popular',)},
        ),
    ]
