# Generated by Django 2.2.4 on 2021-01-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0092_auto_20210130_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planta',
            options={'ordering': ('nombre_popular', 'variedad')},
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre_popular',
            field=models.CharField(max_length=200),
        ),
    ]
