# Generated by Django 2.2.4 on 2021-02-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0093_auto_20210130_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='aporque',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='epocas',
            field=models.ManyToManyField(blank=True, related_name='fichas', to='plantas.Epoca'),
        ),
    ]
