# Generated by Django 2.2.4 on 2021-02-14 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0094_auto_20210214_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuente',
            old_name='articulo',
            new_name='nombre_revista',
        ),
        migrations.AlterField(
            model_name='autororden',
            name='fuente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autores_ordenados', to='plantas.Fuente'),
        ),
    ]
