# Generated by Django 2.2.4 on 2021-02-15 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0095_auto_20210214_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='epoca',
            options={'ordering': ['tipo']},
        ),
        migrations.AlterField(
            model_name='epoca',
            name='tipo',
            field=models.CharField(choices=[('AL', 'Almácigo'), ('SI', 'Siembra'), ('TR', 'Trasplante'), ('CO', 'Cosecha')], default=('AL', 'Almácigo'), max_length=20),
        ),
    ]
