# Generated by Django 2.2.4 on 2021-05-02 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plantas', '0096_auto_20210215_0234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaccion',
            old_name='relacion',
            new_name='observaciones',
        ),
        migrations.RemoveField(
            model_name='interaccion',
            name='target',
        ),
        migrations.AddField(
            model_name='interaccion',
            name='objetivos',
            field=models.ManyToManyField(to='plantas.Planta'),
        ),
        migrations.RemoveField(
            model_name='interaccion',
            name='actor',
        ),
        migrations.AddField(
            model_name='interaccion',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaciones', to='plantas.Planta'),
        ),
        migrations.AlterField(
            model_name='interaccion',
            name='tipo',
            field=models.CharField(choices=[('F', 'Favorable'), ('P', 'Perjudicial')], default='F', max_length=10),
        ),
    ]
